package entities;
// Generated 30/09/2018 8:02:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chdg4K2Items generated by hbm2java
 */
public class Chdg4K2Items  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String alias;
     private int catid;
     private short published;
     private String introtext;
     private String fulltext;
     private String video;
     private String gallery;
     private String extraFields;
     private String extraFieldsSearch;
     private Date created;
     private int createdBy;
     private String createdByAlias;
     private int checkedOut;
     private Date checkedOutTime;
     private Date modified;
     private int modifiedBy;
     private Date publishUp;
     private Date publishDown;
     private short trash;
     private int access;
     private int ordering;
     private short featured;
     private int featuredOrdering;
     private String imageCaption;
     private String imageCredits;
     private String videoCaption;
     private String videoCredits;
     private int hits;
     private String params;
     private String metadesc;
     private String metadata;
     private String metakey;
     private String plugins;
     private String language;

    public Chdg4K2Items() {
    }

	
    public Chdg4K2Items(String title, int catid, short published, String introtext, String fulltext, String extraFieldsSearch, Date created, int createdBy, String createdByAlias, int checkedOut, Date checkedOutTime, Date modified, int modifiedBy, Date publishUp, Date publishDown, short trash, int access, int ordering, short featured, int featuredOrdering, String imageCaption, String imageCredits, String videoCaption, String videoCredits, int hits, String params, String metadesc, String metadata, String metakey, String plugins, String language) {
        this.title = title;
        this.catid = catid;
        this.published = published;
        this.introtext = introtext;
        this.fulltext = fulltext;
        this.extraFieldsSearch = extraFieldsSearch;
        this.created = created;
        this.createdBy = createdBy;
        this.createdByAlias = createdByAlias;
        this.checkedOut = checkedOut;
        this.checkedOutTime = checkedOutTime;
        this.modified = modified;
        this.modifiedBy = modifiedBy;
        this.publishUp = publishUp;
        this.publishDown = publishDown;
        this.trash = trash;
        this.access = access;
        this.ordering = ordering;
        this.featured = featured;
        this.featuredOrdering = featuredOrdering;
        this.imageCaption = imageCaption;
        this.imageCredits = imageCredits;
        this.videoCaption = videoCaption;
        this.videoCredits = videoCredits;
        this.hits = hits;
        this.params = params;
        this.metadesc = metadesc;
        this.metadata = metadata;
        this.metakey = metakey;
        this.plugins = plugins;
        this.language = language;
    }
    public Chdg4K2Items(String title, String alias, int catid, short published, String introtext, String fulltext, String video, String gallery, String extraFields, String extraFieldsSearch, Date created, int createdBy, String createdByAlias, int checkedOut, Date checkedOutTime, Date modified, int modifiedBy, Date publishUp, Date publishDown, short trash, int access, int ordering, short featured, int featuredOrdering, String imageCaption, String imageCredits, String videoCaption, String videoCredits, int hits, String params, String metadesc, String metadata, String metakey, String plugins, String language) {
       this.title = title;
       this.alias = alias;
       this.catid = catid;
       this.published = published;
       this.introtext = introtext;
       this.fulltext = fulltext;
       this.video = video;
       this.gallery = gallery;
       this.extraFields = extraFields;
       this.extraFieldsSearch = extraFieldsSearch;
       this.created = created;
       this.createdBy = createdBy;
       this.createdByAlias = createdByAlias;
       this.checkedOut = checkedOut;
       this.checkedOutTime = checkedOutTime;
       this.modified = modified;
       this.modifiedBy = modifiedBy;
       this.publishUp = publishUp;
       this.publishDown = publishDown;
       this.trash = trash;
       this.access = access;
       this.ordering = ordering;
       this.featured = featured;
       this.featuredOrdering = featuredOrdering;
       this.imageCaption = imageCaption;
       this.imageCredits = imageCredits;
       this.videoCaption = videoCaption;
       this.videoCredits = videoCredits;
       this.hits = hits;
       this.params = params;
       this.metadesc = metadesc;
       this.metadata = metadata;
       this.metakey = metakey;
       this.plugins = plugins;
       this.language = language;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public int getCatid() {
        return this.catid;
    }
    
    public void setCatid(int catid) {
        this.catid = catid;
    }
    public short getPublished() {
        return this.published;
    }
    
    public void setPublished(short published) {
        this.published = published;
    }
    public String getIntrotext() {
        return this.introtext;
    }
    
    public void setIntrotext(String introtext) {
        this.introtext = introtext;
    }
    public String getFulltext() {
        return this.fulltext;
    }
    
    public void setFulltext(String fulltext) {
        this.fulltext = fulltext;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public String getGallery() {
        return this.gallery;
    }
    
    public void setGallery(String gallery) {
        this.gallery = gallery;
    }
    public String getExtraFields() {
        return this.extraFields;
    }
    
    public void setExtraFields(String extraFields) {
        this.extraFields = extraFields;
    }
    public String getExtraFieldsSearch() {
        return this.extraFieldsSearch;
    }
    
    public void setExtraFieldsSearch(String extraFieldsSearch) {
        this.extraFieldsSearch = extraFieldsSearch;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }
    public String getCreatedByAlias() {
        return this.createdByAlias;
    }
    
    public void setCreatedByAlias(String createdByAlias) {
        this.createdByAlias = createdByAlias;
    }
    public int getCheckedOut() {
        return this.checkedOut;
    }
    
    public void setCheckedOut(int checkedOut) {
        this.checkedOut = checkedOut;
    }
    public Date getCheckedOutTime() {
        return this.checkedOutTime;
    }
    
    public void setCheckedOutTime(Date checkedOutTime) {
        this.checkedOutTime = checkedOutTime;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public int getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(int modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getPublishUp() {
        return this.publishUp;
    }
    
    public void setPublishUp(Date publishUp) {
        this.publishUp = publishUp;
    }
    public Date getPublishDown() {
        return this.publishDown;
    }
    
    public void setPublishDown(Date publishDown) {
        this.publishDown = publishDown;
    }
    public short getTrash() {
        return this.trash;
    }
    
    public void setTrash(short trash) {
        this.trash = trash;
    }
    public int getAccess() {
        return this.access;
    }
    
    public void setAccess(int access) {
        this.access = access;
    }
    public int getOrdering() {
        return this.ordering;
    }
    
    public void setOrdering(int ordering) {
        this.ordering = ordering;
    }
    public short getFeatured() {
        return this.featured;
    }
    
    public void setFeatured(short featured) {
        this.featured = featured;
    }
    public int getFeaturedOrdering() {
        return this.featuredOrdering;
    }
    
    public void setFeaturedOrdering(int featuredOrdering) {
        this.featuredOrdering = featuredOrdering;
    }
    public String getImageCaption() {
        return this.imageCaption;
    }
    
    public void setImageCaption(String imageCaption) {
        this.imageCaption = imageCaption;
    }
    public String getImageCredits() {
        return this.imageCredits;
    }
    
    public void setImageCredits(String imageCredits) {
        this.imageCredits = imageCredits;
    }
    public String getVideoCaption() {
        return this.videoCaption;
    }
    
    public void setVideoCaption(String videoCaption) {
        this.videoCaption = videoCaption;
    }
    public String getVideoCredits() {
        return this.videoCredits;
    }
    
    public void setVideoCredits(String videoCredits) {
        this.videoCredits = videoCredits;
    }
    public int getHits() {
        return this.hits;
    }
    
    public void setHits(int hits) {
        this.hits = hits;
    }
    public String getParams() {
        return this.params;
    }
    
    public void setParams(String params) {
        this.params = params;
    }
    public String getMetadesc() {
        return this.metadesc;
    }
    
    public void setMetadesc(String metadesc) {
        this.metadesc = metadesc;
    }
    public String getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }
    public String getMetakey() {
        return this.metakey;
    }
    
    public void setMetakey(String metakey) {
        this.metakey = metakey;
    }
    public String getPlugins() {
        return this.plugins;
    }
    
    public void setPlugins(String plugins) {
        this.plugins = plugins;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }




}


