package entities;
// Generated 30/09/2018 8:02:40 PM by Hibernate Tools 4.3.1



import java.io.Serializable;
import java.util.Date;

/**
 * Chdg4ArtifactgameCard generated by hbm2java
 */
public class Chdg4ArtifactgameCard  implements Serializable {


     private int id;
     private Integer jid;
     private String name;
     private String type;
     private String subtype;
     private String rarity;
     private String color;
     private boolean revealed;
     private Integer attack;
     private Integer armor;
     private Integer health;
     private Integer mana;
     private Integer gold;
     private String skills;
     private String effect;
     private String effectType;
     private String sigCard;
     private String sigOf;
     private Date updateTime;
     private Integer sigId;
     private Integer sigMana;
     private Integer sigCardId;
     private String skillString;

    public String getSkillString() {
        return skillString;
    }

    public void setSkillString(String skillString) {
        this.skillString = skillString;
    }

    public Integer getSigCardId() {
        return sigCardId;
    }

    public void setSigCardId(Integer sigCardId) {
        this.sigCardId = sigCardId;
    }

    public boolean isRevealed() {
        return revealed;
    }

    public Integer getSigId() {
        return sigId;
    }

    public void setSigId(Integer sigId) {
        this.sigId = sigId;
    }

    public Integer getSigMana() {
        return sigMana;
    }

    public void setSigMana(Integer sigMana) {
        this.sigMana = sigMana;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


    public Chdg4ArtifactgameCard(){

    }

    public Chdg4ArtifactgameCard(Integer jid, String name, String type, String subtype, String rarity, String color,
                    boolean revealed, Integer attack, Integer armor, Integer health, Integer mana, Integer gold,
                    String skills, String effect, String effectType, String sigCard, String sigOf, Date updateTime) {

       this.jid = jid;
       this.name = name;
       this.type = type;
       this.subtype = subtype;
       this.rarity = rarity;
       this.color = color;
       this.revealed = revealed;
       this.attack = attack;
       this.armor = armor;
       this.health = health;
       this.mana = mana;
       this.gold = gold;
       this.skills = skills;
       this.effect = effect;
       this.effectType = effectType;
       this.sigCard = sigCard;
       this.sigOf = sigOf;
       this.updateTime = updateTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getJid() {
        return this.jid;
    }
    
    public void setJid(Integer jid) {
        this.jid = jid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getSubtype() {
        return this.subtype;
    }
    
    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }
    public String getRarity() {
        return this.rarity;
    }
    
    public void setRarity(String rarity) {
        this.rarity = rarity;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public boolean getRevealed() {
        return this.revealed;
    }
    
    public void setRevealed(boolean revealed) {
        this.revealed = revealed;
    }
    public Integer getAttack() {
        return this.attack;
    }
    
    public void setAttack(Integer attack) {
        this.attack = attack;
    }
    public Integer getArmor() {
        return this.armor;
    }
    
    public void setArmor(Integer armor) {
        this.armor = armor;
    }
    public Integer getHealth() {
        return this.health;
    }
    
    public void setHealth(Integer health) {
        this.health = health;
    }
    public Integer getMana() {
        return this.mana;
    }
    
    public void setMana(Integer mana) {
        this.mana = mana;
    }
    public Integer getGold() {
        return this.gold;
    }
    
    public void setGold(Integer gold) {
        this.gold = gold;
    }
    public String getSkills() {
        return this.skills;
    }
    
    public void setSkills(String skills) {
        this.skills = skills;
    }
    public String getEffect() {
        return this.effect;
    }
    
    public void setEffect(String effect) {
        this.effect = effect;
    }
    public String getEffectType() {
        return this.effectType;
    }
    
    public void setEffectType(String effectType) {
        this.effectType = effectType;
    }
    public String getSigCard() {
        return this.sigCard;
    }
    
    public void setSigCard(String sigCard) {
        this.sigCard = sigCard;
    }
    public String getSigOf() {
        return this.sigOf;
    }
    
    public void setSigOf(String sigOf) {
        this.sigOf = sigOf;
    }




}


